### ISSUE TITLE
Nested aliases don't work

### ISSUE THREAD

**Issue by twidi** [tamentis/prwd#8]
As stated in the `prwdrc` man page, I should be able to do this:

```
alias TW /home/twidi
alias *dev TW/dev
```
But the `*dev` alias doesn't work.

It works only if I don't use nested alias:

```
alias TW /home/twidi
alias *dev /home/twidi/dev
```

Also, about nesting, the man page says "one level deep", so I guees I cannot use something like

```
alias *dev /home/twidi/dev
alias *foo *dev/some/projects/foo
```

won't work ?

**Comment by tamentis** [comment]
Sorry for the delay, I believe that should fix your problem. I added a test for it.
